//
//  MRAuthorizationResult.h
//  mr-mail-sdk
//
//  Created by Evgeniy Yurtaev on 07/08/2019.
//  Copyright © 2019 Mail.Ru. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, MRSDKAuthorizationResultType) {
    MRSDKAuthorizationResultTypeCode,
    MRSDKAuthorizationResultTypeToken,
};

@interface MRSDKAuthorizationResult : NSObject

@property (nonatomic, readonly, assign) MRSDKAuthorizationResultType type;
/// The authorization code generated by the authorization server
/// Set when the ResultType is Code
@property (nonatomic, nullable, readonly, copy) NSString *authorizationCode;
/// The PKCE code verifier
/// May be set when the ResultType is Code and PKCE is enabled
@property (nonatomic, nullable, readonly, copy) NSString *codeVerifier;
/// The refresh token generated by the authorization server
/// Set when the ResultType is Token
@property (nonatomic, nullable, readonly, copy) NSString *refreshToken;
/// The access token generated by the authorization server
/// Set when the ResultType is Token
@property (nonatomic, nullable, readonly, copy) NSString *accessToken;
/// The approximate expiration date & time of the access token
@property (nonatomic, nullable, readonly, strong) NSDate *accessTokenExpirationDate;

- (instancetype)initWithAuthorizationCode:(NSString *)authorizationCode
                             codeVerifier:(nullable NSString *)codeVerifier NS_DESIGNATED_INITIALIZER;

- (instancetype)initWithRefreshToken:(NSString *)refreshToken
                         accessToken:(NSString *)accessToken
           accessTokenExpirationDate:(nullable NSDate *)accessTokenExpirationDate NS_DESIGNATED_INITIALIZER;

+ (instancetype)new NS_UNAVAILABLE;
- (instancetype)init NS_UNAVAILABLE;

@end

NS_ASSUME_NONNULL_END
